### ISSUE TITLE
Certificat intermédiaire de Gandi

### ISSUE THREAD

**Issue by kslimani** [jlecour/ssl-gandi-nginx-debian#5]
Bonjour,

il semble que Gandi ai ajouté le certificat _cross signed Comodo_ au fichier `http://www.gandi.net/static/CAs/GandiStandardSSLCA2.pem`.

Du coup si on suis le guide, le certificat est concaténé deux fois.
_(ou j'ai peut être pas bien compris !)_

**Comment by jlecour** [comment]
Ça l'air d'être effectivement le cas.

Je regarde ça en détail dès que je peux et j'adapte le guide si besoin.

Merci pour l'info.
