### ISSUE TITLE
AddTrust_External_Root.pem

### ISSUE THREAD

**Issue by kopax** [jlecour/ssl-gandi-nginx-debian#7]
Bonjour,

J'essai d'installer un certificat gandi sur nginx, j'en suis bloquer à l'étape `stapling`

A quoi correspond ce fichier : `AddTrust_External_Root.pem` ?

je viens de trouvé ceci : [https://support.comodo.com/index.php?/Default/Knowledgebase/Article/View/620/1/which-is-root-which-is-intermediate](support.comodo.com)

Lequel faut prendre ?

C'est vraiment une galère ces certificats Gandi, ils n'ont jamais pensé à nous fournir les fichiers eux même ?

**Comment by jlecour** [comment]
Salut @kopax 

Ce fichier est fourni par Comodo et c'est leur certificat racine.
Par rapport à la liste que tu as trouvée sur leur site, je ne sais pas non plus lequel il faudrait prendre. Il est normalement déjà présent sur ta machine.

**Comment by kopax** [comment]
@jlecour tu en avais deja in sur ta machine? Quel Is et ou? Je suis sur debian, pas vu l'ombre s'un certificate comme celui LA -_-. Peux tu eventuellement montrer ta version ?

**Comment by jlecour** [comment]
```
# cat /etc/debian_version
7.8

# ls /etc/ssl/certs/Add*
/etc/ssl/certs/AddTrust_External_Root.pem
/etc/ssl/certs/AddTrust_Public_Services_Root.pem
/etc/ssl/certs/AddTrust_Low-Value_Services_Root.pem
/etc/ssl/certs/AddTrust_Qualified_Certificates_Root.pem
```

**Comment by jlecour** [comment]
Il est possible qu'il te faille le paquet `ca-certificates` mais ça serait étonnant qu'il ne soit pas déjà installé.

**Comment by kopax** [comment]
En faites je les ais mais je ne savais pas ou chercher.

Je ne mettais pas positionner dans le repertoir `/etc/ssl/` pour faire les commandes.

J'avais dans l'intention d'utiliser un container docker nginx comme load balancer et de placer les certificats dans ce repertoire à ce moment la. 

C'est peut-être utile de l'indiquer dans le tuto ?

 _pour les newbies des certificats signés comme moi_

**Comment by ariden83** [comment]
AddTrust_External_Root.pem >   https://support.comodo.com/index.php?/Knowledgebase/Article/View/945/0/root-addtrust-external-ca-root
